// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: address.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createAddress = `-- name: CreateAddress :one
INSERT INTO address(
    id,
    customer_id,
    "type",
    first_name,
    last_name,
    address1,
    address2,
    city,
    province,
    province_code,
    company,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, customer_id, type, first_name, last_name, address1, address2, city, province, province_code, company, created_at, updated_at
`

type CreateAddressParams struct {
	ID           uuid.UUID      `json:"id"`
	CustomerID   uuid.UUID      `json:"customer_id"`
	Type         string         `json:"type"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Address1     sql.NullString `json:"address1"`
	Address2     sql.NullString `json:"address2"`
	City         sql.NullString `json:"city"`
	Province     sql.NullString `json:"province"`
	ProvinceCode sql.NullString `json:"province_code"`
	Company      sql.NullString `json:"company"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) CreateAddress(ctx context.Context, arg CreateAddressParams) (Address, error) {
	row := q.db.QueryRowContext(ctx, createAddress,
		arg.ID,
		arg.CustomerID,
		arg.Type,
		arg.FirstName,
		arg.LastName,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.Province,
		arg.ProvinceCode,
		arg.Company,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Address
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Type,
		&i.FirstName,
		&i.LastName,
		&i.Address1,
		&i.Address2,
		&i.City,
		&i.Province,
		&i.ProvinceCode,
		&i.Company,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAddressByCustomer = `-- name: GetAddressByCustomer :many
SELECT
    id,
    "type",
    first_name,
    last_name,
    address1,
    address2,
    city,
    province,
    province_code,
    company,
    updated_at
FROM address
WHERE customer_id = $1
`

type GetAddressByCustomerRow struct {
	ID           uuid.UUID      `json:"id"`
	Type         string         `json:"type"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Address1     sql.NullString `json:"address1"`
	Address2     sql.NullString `json:"address2"`
	City         sql.NullString `json:"city"`
	Province     sql.NullString `json:"province"`
	ProvinceCode sql.NullString `json:"province_code"`
	Company      sql.NullString `json:"company"`
	UpdatedAt    time.Time      `json:"updated_at"`
}

func (q *Queries) GetAddressByCustomer(ctx context.Context, customerID uuid.UUID) ([]GetAddressByCustomerRow, error) {
	rows, err := q.db.QueryContext(ctx, getAddressByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAddressByCustomerRow
	for rows.Next() {
		var i GetAddressByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.FirstName,
			&i.LastName,
			&i.Address1,
			&i.Address2,
			&i.City,
			&i.Province,
			&i.ProvinceCode,
			&i.Company,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeAddress = `-- name: RemoveAddress :exec
DELETE FROM address
WHERE id = $1
`

func (q *Queries) RemoveAddress(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeAddress, id)
	return err
}

const updateAddress = `-- name: UpdateAddress :exec
UPDATE address
SET
    customer_id = $1,
    first_name = $2,
    last_name = $3,
    address1 = $4,
    address2 = $5,
    city = $6,
    province = $7,
    province_code = $8,
    company = $9,
    updated_at = $10
WHERE id = $11
`

type UpdateAddressParams struct {
	CustomerID   uuid.UUID      `json:"customer_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Address1     sql.NullString `json:"address1"`
	Address2     sql.NullString `json:"address2"`
	City         sql.NullString `json:"city"`
	Province     sql.NullString `json:"province"`
	ProvinceCode sql.NullString `json:"province_code"`
	Company      sql.NullString `json:"company"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ID           uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateAddress(ctx context.Context, arg UpdateAddressParams) error {
	_, err := q.db.ExecContext(ctx, updateAddress,
		arg.CustomerID,
		arg.FirstName,
		arg.LastName,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.Province,
		arg.ProvinceCode,
		arg.Company,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAddressByTypeAndCustomer = `-- name: UpdateAddressByTypeAndCustomer :exec
UPDATE address
SET
    customer_id = $1,
    first_name = $2,
    last_name = $3,
    address1 = $4,
    address2 = $5,
    city = $6,
    province = $7,
    province_code = $8,
    company = $9,
    updated_at = $10
WHERE type = $11 AND
customer_id = $12
`

type UpdateAddressByTypeAndCustomerParams struct {
	CustomerID   uuid.UUID      `json:"customer_id"`
	FirstName    string         `json:"first_name"`
	LastName     string         `json:"last_name"`
	Address1     sql.NullString `json:"address1"`
	Address2     sql.NullString `json:"address2"`
	City         sql.NullString `json:"city"`
	Province     sql.NullString `json:"province"`
	ProvinceCode sql.NullString `json:"province_code"`
	Company      sql.NullString `json:"company"`
	UpdatedAt    time.Time      `json:"updated_at"`
	Type         string         `json:"type"`
	CustomerID_2 uuid.UUID      `json:"customer_id_2"`
}

func (q *Queries) UpdateAddressByTypeAndCustomer(ctx context.Context, arg UpdateAddressByTypeAndCustomerParams) error {
	_, err := q.db.ExecContext(ctx, updateAddressByTypeAndCustomer,
		arg.CustomerID,
		arg.FirstName,
		arg.LastName,
		arg.Address1,
		arg.Address2,
		arg.City,
		arg.Province,
		arg.ProvinceCode,
		arg.Company,
		arg.UpdatedAt,
		arg.Type,
		arg.CustomerID_2,
	)
	return err
}
