// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: customers.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers(
    first_name,
    last_name,
    created_at,
    updated_at
) VALUES(
    $1, $2, $3, $4
)
RETURNING id, order_id, first_name, last_name, created_at, updated_at
`

type CreateCustomerParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
    first_name,
    last_name,
    updated_at
FROM customers
WHERE id = $1
`

type GetCustomerByIDRow struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, id uuid.UUID) (GetCustomerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.UpdatedAt)
	return i, err
}

const getCustomers = `-- name: GetCustomers :many
SELECT
    first_name,
    last_name,
    updated_at
FROM customers
LIMIT $1 OFFSET $2
`

type GetCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetCustomersRow struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomers(ctx context.Context, arg GetCustomersParams) ([]GetCustomersRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersRow
	for rows.Next() {
		var i GetCustomersRow
		if err := rows.Scan(&i.FirstName, &i.LastName, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomersByName = `-- name: GetCustomersByName :many
SELECT
    first_name,
    last_name,
    updated_at
FROM customers
WHERE CONCAT(first_name, ' ', last_name) SIMILAR TO $1
LIMIT 10
`

type GetCustomersByNameRow struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomersByName(ctx context.Context, similarToEscape string) ([]GetCustomersByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersByName, similarToEscape)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersByNameRow
	for rows.Next() {
		var i GetCustomersByNameRow
		if err := rows.Scan(&i.FirstName, &i.LastName, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET
    first_name = $1,
    last_name = $2,
    updated_at = $3
WHERE id = $4
RETURNING id, order_id, first_name, last_name, created_at, updated_at
`

type UpdateCustomerParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRowContext(ctx, updateCustomer,
		arg.FirstName,
		arg.LastName,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
