// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: customers.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createCustomer = `-- name: CreateCustomer :execresult
INSERT INTO customers(
    first_name,
    last_name,
    created_at,
    updated_at
) VALUES(
    ?, ?, ?, ?
)
`

type CreateCustomerParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCustomer,
		arg.FirstName,
		arg.LastName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getCustomerByID = `-- name: GetCustomerByID :one
SELECT
    first_name,
    last_name,
    updated_at
FROM customers
WHERE id = ?
`

type GetCustomerByIDRow struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomerByID(ctx context.Context, id []byte) (GetCustomerByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getCustomerByID, id)
	var i GetCustomerByIDRow
	err := row.Scan(&i.FirstName, &i.LastName, &i.UpdatedAt)
	return i, err
}

const getCustomersByName = `-- name: GetCustomersByName :many
SELECT
    first_name,
    last_name,
    updated_at
FROM customers
WHERE CONCAT(first_name, ' ', last_name) REGEXP ?
LIMIT 10
`

type GetCustomersByNameRow struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetCustomersByName(ctx context.Context) ([]GetCustomersByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, getCustomersByName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCustomersByNameRow
	for rows.Next() {
		var i GetCustomersByNameRow
		if err := rows.Scan(&i.FirstName, &i.LastName, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :execresult
UPDATE customers
SET
    first_name = ?,
    last_name = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateCustomerParams struct {
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        []byte    `json:"id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateCustomer,
		arg.FirstName,
		arg.LastName,
		arg.UpdatedAt,
		arg.ID,
	)
}
