// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: google_oauth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOAuthRecord = `-- name: CreateOAuthRecord :one
INSERT INTO google_oauth(
    id,
    user_id,
    cookie_token,
    google_id,
    email,
    picture,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, cookie_secret, cookie_token, google_id, email, picture, created_at, updated_at
`

type CreateOAuthRecordParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	CookieToken []byte         `json:"cookie_token"`
	GoogleID    string         `json:"google_id"`
	Email       string         `json:"email"`
	Picture     sql.NullString `json:"picture"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (q *Queries) CreateOAuthRecord(ctx context.Context, arg CreateOAuthRecordParams) (GoogleOauth, error) {
	row := q.db.QueryRowContext(ctx, createOAuthRecord,
		arg.ID,
		arg.UserID,
		arg.CookieToken,
		arg.GoogleID,
		arg.Email,
		arg.Picture,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i GoogleOauth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CookieSecret,
		&i.CookieToken,
		&i.GoogleID,
		&i.Email,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, user_id, cookie_secret, cookie_token, google_id, email, picture, created_at, updated_at FROM google_oauth
WHERE google_id = $1
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (GoogleOauth, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i GoogleOauth
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CookieSecret,
		&i.CookieToken,
		&i.GoogleID,
		&i.Email,
		&i.Picture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
