// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: google_oauth.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createOAuthRecord = `-- name: CreateOAuthRecord :exec
INSERT INTO google_oauth(
    id,
    google_id,
    email,
    picture,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
`

type CreateOAuthRecordParams struct {
	ID        uuid.UUID      `json:"id"`
	GoogleID  string         `json:"google_id"`
	Email     string         `json:"email"`
	Picture   sql.NullString `json:"picture"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateOAuthRecord(ctx context.Context, arg CreateOAuthRecordParams) error {
	_, err := q.db.ExecContext(ctx, createOAuthRecord,
		arg.ID,
		arg.GoogleID,
		arg.Email,
		arg.Picture,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
