// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: shopify_location.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createShopifyLocation = `-- name: CreateShopifyLocation :exec
INSERT INTO shopify_location(
    ID,
    shopify_warehouse_name,
    shopify_location_id,
    warehouse_name,
    created_at,
    updated_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateShopifyLocationParams struct {
	ID                   uuid.UUID `json:"id"`
	ShopifyWarehouseName string    `json:"shopify_warehouse_name"`
	ShopifyLocationID    string    `json:"shopify_location_id"`
	WarehouseName        string    `json:"warehouse_name"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

func (q *Queries) CreateShopifyLocation(ctx context.Context, arg CreateShopifyLocationParams) error {
	_, err := q.db.ExecContext(ctx, createShopifyLocation,
		arg.ID,
		arg.ShopifyWarehouseName,
		arg.ShopifyLocationID,
		arg.WarehouseName,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const getShopifyLocationByWarehouse = `-- name: GetShopifyLocationByWarehouse :one
SELECT
    id,
    shopify_warehouse_name,
    shopify_location_id,
    warehouse_name,
    created_at
FROM shopify_location
WHERE warehouse_name = $1
`

type GetShopifyLocationByWarehouseRow struct {
	ID                   uuid.UUID `json:"id"`
	ShopifyWarehouseName string    `json:"shopify_warehouse_name"`
	ShopifyLocationID    string    `json:"shopify_location_id"`
	WarehouseName        string    `json:"warehouse_name"`
	CreatedAt            time.Time `json:"created_at"`
}

func (q *Queries) GetShopifyLocationByWarehouse(ctx context.Context, warehouseName string) (GetShopifyLocationByWarehouseRow, error) {
	row := q.db.QueryRowContext(ctx, getShopifyLocationByWarehouse, warehouseName)
	var i GetShopifyLocationByWarehouseRow
	err := row.Scan(
		&i.ID,
		&i.ShopifyWarehouseName,
		&i.ShopifyLocationID,
		&i.WarehouseName,
		&i.CreatedAt,
	)
	return i, err
}

const removeShopifyLocationMap = `-- name: RemoveShopifyLocationMap :exec
DELETE FROM shopify_location
WHERE id = $1
`

func (q *Queries) RemoveShopifyLocationMap(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removeShopifyLocationMap, id)
	return err
}

const updateShopifyLocation = `-- name: UpdateShopifyLocation :exec
UPDATE shopify_location
SET
    shopify_warehouse_name = $1,
    shopify_location_id = $2,
    updated_at = $3
WHERE warehouse_name = $4
`

type UpdateShopifyLocationParams struct {
	ShopifyWarehouseName string    `json:"shopify_warehouse_name"`
	ShopifyLocationID    string    `json:"shopify_location_id"`
	UpdatedAt            time.Time `json:"updated_at"`
	WarehouseName        string    `json:"warehouse_name"`
}

func (q *Queries) UpdateShopifyLocation(ctx context.Context, arg UpdateShopifyLocationParams) error {
	_, err := q.db.ExecContext(ctx, updateShopifyLocation,
		arg.ShopifyWarehouseName,
		arg.ShopifyLocationID,
		arg.UpdatedAt,
		arg.WarehouseName,
	)
	return err
}
