// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: users.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (
    name,
    email,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?
)
`

type CreateUserParams struct {
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getUserByApiKey = `-- name: GetUserByApiKey :one
SELECT id, webhook_token, created_at, updated_at, name, email, api_key FROM users
WHERE api_key = ?
LIMIT 1
`

func (q *Queries) GetUserByApiKey(ctx context.Context, apiKey []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebhookToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.ApiKey,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, webhook_token, created_at, updated_at, name, email, api_key FROM users
WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebhookToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.ApiKey,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT
    name
FROM users
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	err := row.Scan(&name)
	return name, err
}

const getUsers = `-- name: GetUsers :one
SELECT id, webhook_token, created_at, updated_at, name, email, api_key FROM users LIMIT 1
`

func (q *Queries) GetUsers(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsers)
	var i User
	err := row.Scan(
		&i.ID,
		&i.WebhookToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.ApiKey,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :execresult
UPDATE users 
SET
    name = ?,
    email = ?,
    updated_at = ?
WHERE id = ?
`

type UpdateUserParams struct {
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	UpdatedAt time.Time `json:"updated_at"`
	ID        []byte    `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.UpdatedAt,
		arg.ID,
	)
}

const validateWebhookByUser = `-- name: ValidateWebhookByUser :one
SELECT
    name
FROM users
WHERE 
webhook_token = ? AND name = ?
`

type ValidateWebhookByUserParams struct {
	WebhookToken []byte `json:"webhook_token"`
	Name         string `json:"name"`
}

func (q *Queries) ValidateWebhookByUser(ctx context.Context, arg ValidateWebhookByUserParams) (string, error) {
	row := q.db.QueryRowContext(ctx, validateWebhookByUser, arg.WebhookToken, arg.Name)
	var name string
	err := row.Scan(&name)
	return name, err
}
