// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.0
// source: variants_pricing.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createVariantPricing = `-- name: CreateVariantPricing :one
INSERT INTO variant_pricing(
    id,
    variant_id,
    name,
    value,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, variant_id, name, value, created_at, updated_at
`

type CreateVariantPricingParams struct {
	ID        uuid.UUID      `json:"id"`
	VariantID uuid.UUID      `json:"variant_id"`
	Name      string         `json:"name"`
	Value     sql.NullString `json:"value"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
}

func (q *Queries) CreateVariantPricing(ctx context.Context, arg CreateVariantPricingParams) (VariantPricing, error) {
	row := q.db.QueryRowContext(ctx, createVariantPricing,
		arg.ID,
		arg.VariantID,
		arg.Name,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i VariantPricing
	err := row.Scan(
		&i.ID,
		&i.VariantID,
		&i.Name,
		&i.Value,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantPricing = `-- name: GetVariantPricing :many
SELECT 
    name,
    value
FROM variant_pricing
WHERE variant_id = $1
`

type GetVariantPricingRow struct {
	Name  string         `json:"name"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) GetVariantPricing(ctx context.Context, variantID uuid.UUID) ([]GetVariantPricingRow, error) {
	rows, err := q.db.QueryContext(ctx, getVariantPricing, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariantPricingRow
	for rows.Next() {
		var i GetVariantPricingRow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariantPricingBySKU = `-- name: GetVariantPricingBySKU :many
SELECT
    name,
    value
FROM variant_pricing
WHERE variant_id IN (
    SELECT id FROM variants
    WHERE sku = $1
)
`

type GetVariantPricingBySKURow struct {
	Name  string         `json:"name"`
	Value sql.NullString `json:"value"`
}

func (q *Queries) GetVariantPricingBySKU(ctx context.Context, sku string) ([]GetVariantPricingBySKURow, error) {
	rows, err := q.db.QueryContext(ctx, getVariantPricingBySKU, sku)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariantPricingBySKURow
	for rows.Next() {
		var i GetVariantPricingBySKURow
		if err := rows.Scan(&i.Name, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePricing = `-- name: RemovePricing :exec
DELETE FROM variant_pricing
WHERE id = $1
`

func (q *Queries) RemovePricing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, removePricing, id)
	return err
}

const updateVariantPricing = `-- name: UpdateVariantPricing :exec
UPDATE variant_pricing
SET
    value = $1
WHERE variant_id IN (
    SELECT id FROM variants
    WHERE sku = $2
) AND name = $3
`

type UpdateVariantPricingParams struct {
	Value sql.NullString `json:"value"`
	Sku   string         `json:"sku"`
	Name  string         `json:"name"`
}

func (q *Queries) UpdateVariantPricing(ctx context.Context, arg UpdateVariantPricingParams) error {
	_, err := q.db.ExecContext(ctx, updateVariantPricing, arg.Value, arg.Sku, arg.Name)
	return err
}
