// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: variants_qty.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createVariantQty = `-- name: CreateVariantQty :execresult
INSERT INTO variant_qty(
    id,
    variant_id,
    name,
    value,
    created_at,
    updated_at
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateVariantQtyParams struct {
	ID        string    `json:"id"`
	VariantID string    `json:"variant_id"`
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateVariantQty(ctx context.Context, arg CreateVariantQtyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createVariantQty,
		arg.ID,
		arg.VariantID,
		arg.Name,
		arg.Value,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
}

const getVariantQty = `-- name: GetVariantQty :many
SELECT 
    name,
    value,
    updated_at
FROM variant_qty
WHERE variant_id = ?
`

type GetVariantQtyRow struct {
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetVariantQty(ctx context.Context, variantID string) ([]GetVariantQtyRow, error) {
	rows, err := q.db.QueryContext(ctx, getVariantQty, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariantQtyRow
	for rows.Next() {
		var i GetVariantQtyRow
		if err := rows.Scan(&i.Name, &i.Value, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVariantQty = `-- name: UpdateVariantQty :execresult
UPDATE variant_qty
SET
    name = ?,
    value = ?,
    updated_at = ?
WHERE variant_id = ?
`

type UpdateVariantQtyParams struct {
	Name      string    `json:"name"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
	VariantID string    `json:"variant_id"`
}

func (q *Queries) UpdateVariantQty(ctx context.Context, arg UpdateVariantQtyParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateVariantQty,
		arg.Name,
		arg.Value,
		arg.UpdatedAt,
		arg.VariantID,
	)
}
