version: "2"
services:
    postgres:
        restart: always
        container_name: ${DB_NAME}
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - integrator-volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PSW}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - integrator-net

    server:
        build:
            context: ./
            dockerfile: ./setup/server/Dockerfile
        depends_on:
            - postgres
        ports:
            - "${PORT}:${PORT}"
        container_name: ${SERVER_CONTAINER_NAME}
        env_file:
            - .env
        networks:
            - integrator-net
        volumes:
            - ./:/keenan/

volumes:
    integrator-volume:
        driver: local

networks:
    integrator-net:
        driver: bridge
