FROM golang:1.22

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

RUN mkdir keenan && cd keenan
WORKDIR /keenan/

# Migrations
COPY ./ /keenan/

RUN ["chmod", "+x", "/keenan/scripts/migrations.sh"]

ENTRYPOINT [ "/bin/sh", "-c" , "go build -buildvcs=false -o integrator && ./integrator --localhost"]