-- +goose Up
CREATE TABLE users(
    id BINARY(16) PRIMARY KEY UNIQUE NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
    webhook_token BINARY(16) UNIQUE NOT NULL DEFAULT (UUID_TO_BIN(UUID())),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    api_key BINARY(16) UNIQUE NOT NULL DEFAULT (UUID_TO_BIN(UUID()))
);

-- +goose Down
DROP TABLE users;